<?php
/**
 * Объект каталога
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemotractorPhpExtension $this
 * @var array $variables
 * @var iUmiHierarchyElement $page
 */
$page = $this->getPageAndPushToEditable($variables['pageId']);
$pageId = $this->escape($page->getId());
$imageTitle = $this->escape($this->getPageImageTitle($pageId, 'image'));
$imagePath = $this->escape($this->getPageImagePath($pageId, 'image'));
?>
<div class="umi-second-content">
	<div class="content-wrap">
		<?= $this->render($this->macros('core', 'navibar'), 'core/navibar') ?>
		<h1 id="page_main_header" class="h1">
			<span class="h1_content" umi:element-id="<?= $pageId ?>" umi:field-name="h1"
				  umi:empty="<?= $this->escape($this->translate('empty_page_h1')) ?>"><?= $this->escape($page->getValue('h1')) ?></span>
		</h1>
		<div class="object" umi:element-id="<?= $pageId ?>">
			<div class="object_image">
				<a class="object_image_a fancybox-group" title="<?= $imageTitle ?>" href="<?= $imagePath ?>" 
					rel="<?= $this->escape($page->getAltName()) ?>"
					data-caption="<?= $imageTitle ?>">
					<img umi:element-id="<?= $pageId ?>" umi:field-name="image"
					     alt="<?= $this->escape($this->getPageImageAlt($pageId, 'image')) ?>"
					     title="<?= $imageTitle ?>"
					     src="<?= $imagePath ?>">
				</a>
			</div>
			<div class="text" umi:element-id="<?= $pageId ?>" umi:field-name="description"
			     umi:empty="<?= $this->escape($this->translate('empty_page_content')) ?>">
				<?= $page->getValue('description') ?>
			</div>
		</div>
	</div>
</div>
