<?php
/**
 * Фотография в списке
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemotractorPhpExtension $this
 * @var array $variables
 */
$pageId = $this->escape($variables['id']);
$name = isset($variables['name']) ? $this->escape($variables['name']) : '';
$imagePath = $this->escape($this->getPageImagePath($pageId, 'photo'));
?>
<li class="photo tech" umi:element-id="<?= $pageId ?>" umi:region="row" >
	<div class="photo_album_img_div">
		<a class="photo_img fancybox-group" href="<?= $imagePath ?>" title="<?= $name ?>" 
			rel="<?= $this->escape($variables['rel']) ?>" 
			data-fancybox="gallery" 
			data-caption="<?= $name ?>">
			<img umi:element-id="<?= $pageId ?>" umi:field-name="photo"
				 alt="<?= $this->escape($this->getPageImageAlt($pageId, 'photo')) ?>"
				 title="<?= $this->escape($this->getPageImageTitle($pageId, 'photo')) ?>"
				 src="<?= $imagePath ?>">
		</a>
	</div>
	<div class="photo_title">
		<a href="<?= $this->escape($variables['link']) ?>" title="<?= $name ?>" umi:field-name="name"  umi:delete="delete"
		   umi:empty="<?= $this->escape($this->translate('empty_photo_name')) ?>">
			<?= $name ?>
		</a>
	</div>
</li>
