<?php
/**
 * Страница вывода системных ошибок.
 *
 * @see umiTemplaterPHP::ERROR_TEMPLATE
 * @var umiTemplaterPHP|ViewPhpExtension|DemotractorPhpExtension $this
 * @var array $variables
 * @var Exception $error
 */
?>
<div class="row-fluid for-content">
	<div class="container">
		<div class="umi-second-content">
			<div class="content-wrap">
				<h1 class="h1"><?= $this->translate('js-error-occurred') ?></h1>
				<p><?= $error->getMessage() ?></p>
				<?php if ($this->isDebug()): ?>
					<p><?= $error->getTraceAsString() ?></p>
				<?php endif; ?>
			</div>
		</div>
	</div>
</div>