<?php
/**
 * Главное меню (отображается как сайдбар)
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemotractorPhpExtension $this
 * @var array $variables
 */
?>
<div class="for-menu">
	<div class="nav-wrap">
		<div class="row-fluid umi-menu">
			<div class="span12">
				<div class="navbar">
					<div class="navbar-inner">
						<?= $this->render($this->macros('content', 'menu', [null, 2, 0, 1]), 'content/menu') ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
