<?php
/**
 * Список пунктов карты сайта
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemotractorPhpExtension $this
 * @var array $variables
 */
$siteMapItemList = isset($variables['items']) ? $variables['items'] : [];
?>
<?php if (count($siteMapItemList) > 0): ?>
	<ul>
		<?php foreach ($siteMapItemList as $siteMapItem): ?>
			<?= $this->render($siteMapItem, 'content/sitemap_item') ?>
		<?php endforeach; ?>
	</ul>
<?php endif; ?>
